---
- name: Ensure unzip is installed
  package:
    name: unzip

- name: Get chromedriver version
  command: '{{ chromedriver_path }}/{{ chromedriver_bin }} --version'
  register: chromedriver_version_installed
  changed_when: false
  failed_when: false

- name: Get latest chromedriver version
  when: chromedriver_version is not defined or (chromedriver_version == 'latest')
  block:
    - name: Get latest chromedriver's information
      uri:
        url: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
        return_content: yes
      register: chromedriver_latest
      changed_when: false
      failed_when: false

    - name: Set latest chromedriver's version as chromedriver_version fact
      set_fact:
        chromedriver_version: '{{ chromedriver_latest.content }}'

- name: Ensure install directory exists
  file:
    path: '{{ chromedriver_path }}'
    state: directory

- name: Install ChromeDriver
  unarchive:
    src: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"
    dest: '{{ chromedriver_install_prefix }}/bin'
    mode: 0755
    copy: no
  when:  >
    chromedriver_version_installed.rc != 0 or
      "ChromeDriver %s"|format(chromedriver_version) not in chromedriver_version_installed.stdout
