---
- name: Check supported architecture or not
  fail:
    msg: 'Only 64bit Linux is supported'
  when: 'ansible_userspace_bits != "64"'

- import_tasks: install-google-chrome.yml

- import_tasks: install-chromedriver.yml
